# Generated by Django 5.2.6 on 2025-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bustrackr_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("role", models.CharField(default="staff", max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
