# Generated by Django 5.2.8 on 2025-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustrackr_app', '0003_adminaccount_staffaccount_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50)),
                ('bus_company', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
